@startuml
package "src" {
  class main.js
  class axiosClient.js
  class index.html
  class "router/index.js"
  class App.vue {
    <router-view>
  }
  class TheMealDB_API

  package "views" {
    class HomeView {
      general info and meal listing
    }
    class SearchByLetterView {
      search meals by letter
    }
    class SearchByNameView {
      search meals by name
    }
    class SearchByIngredientView {
      search meals by ingredient
    }
    class IngredientsView {
      list of ingredients
    }
    class MealDetailsView {
      meal details
    }
  }

  package "components" {
    class DefaultLayout {
      default layout
    }
    class UnauthenticatedLayout {
      layout for unauthenticated users
    }
    class Navbar {
      navigation bar
    }
    class MealItem {
      card template
    }
    class Notification {
      alerts and notifications
    }
    class Footer {
      footer content
    }
    class FavoriteMeals {
      list of favorite meals
    }
    class PaginateControl {
      pagination controls
    }
    class Login {
      login form
    }
    class Register {
      registration form
    }
    class YoutubeButton {
      YouTube button
    }
  }

  package "resources" {
    class api_register.php
    class api_user.php
    class db.php
    class favorites.php
    class vote.php
  }
}

main.js --> App.vue
App.vue --> "router/index.js"
App.vue --> axiosClient.js
App.vue --> index.html
App.vue --> TheMealDB_API

App.vue --> HomeView
HomeView --> SearchByLetterView
HomeView --> SearchByNameView
HomeView --> SearchByIngredientView
HomeView --> IngredientsView
HomeView --> MealDetailsView

HomeView --> MealItem
HomeView --> Notification
HomeView --> Footer
HomeView --> DefaultLayout
HomeView --> Navbar

DefaultLayout --> FavoriteMeals
DefaultLayout --> PaginateControl
DefaultLayout --> Login
DefaultLayout --> Register
DefaultLayout --> YoutubeButton

UnauthenticatedLayout --> Login
UnauthenticatedLayout --> Register

db.php --> favorites.php
db.php --> api_user.php
db.php --> api_register.php
db.php --> vote.php

api_register.php --> Register
api_user.php --> Login
favorites.php --> FavoriteMeals
vote.php --> FavoriteMeals
@enduml